
user				nginx;

worker_processes	auto;

events
{
	worker_connections 1024;
}

http
{
	server {
		listen 443 ssl;
		server_name ralba-ji.42.fr;

		ssl_certificate /run/secrets/nginx_crt;
		ssl_certificate_key /run/secrets/nginx_key;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;
		
		root /var/www/html;
		index index.php index.html;
		
		location / {
			include /etc/nginx/mime.types;
			try_files $uri $uri/ /index.php?$args;
		}
		
		location ~ \.php$ {
			try_files $uri =404;
			include fastcgi_params;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
			fastcgi_param HTTPS on;
		}
	}
}
